name: BUILD

on:
  push:
  schedule:
    - cron: '1 */8 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos:
          - openlist-git
          - imfile
          - breath-theme-git
          - cromite-bin
          - zen-browser-bin
          - opencode
          - qwen-code
          - wine-cachyos-opt
        include:
          - repos: realesrgan-ncnn-vulkan
            preinstall-pkgs: "vulkan-intel"
          - repos: bilibili-bin
            preinstall-pkgs: "electron28-bin"
      fail-fast: false

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - uses: ./build-aur-action
        with:
          repo-name: ${{ matrix.repos }}
          preinstallPkgs: ${{ matrix.preinstall-pkgs }}

      - uses: actions/upload-artifact@v4
        if-no-files-found: error
        with:
          name: ${{ matrix.repos }}
          path: ./*/*.pkg.tar.zst

  createRepo:
    needs: [buildAUR]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          path: ./downloaded_artifacts

      - name: Display structure of downloaded files
        run: ls -R ./downloaded_artifacts

      - name: Collect all package files
        run: |
          mkdir -p ./collected_packages
          find ./downloaded_artifacts -type f -name "*.tar.zst" -exec cp {} ./collected_packages/ \;
          ls -la ./collected_packages/

      - uses: ./create-repo-action
        with:
          repo_name: vifly
          gpg-privatekey: ${{ secrets.gpg_private_key }}
          gpg-passphrase: ${{ secrets.gpg_passphrase }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: packages
          artifacts: "./repo/*"
          token: ${{ secrets.GITHUB_TOKEN }}
